# Generated by Django 3.2.16 on 2022-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
